### ISSUE TITLE
bundle generation TEMP_FILE_PATH can break parallel builds

### ISSUE THREAD

**Issue by webkodierer** [Microsoft/code-push#436]
Affected version of code push: AFAICT this affects all code push versions. 

Description:

During bundle creation a temp file is used in TMPDIR/CodePushResourcesMap.json 

For concurrent executions (for us this is the case on our continuous integration server) this allows race conditions resulting in unexpected build failures and _maybe_ to other unexpected results. 

First in scripts/recordFilesBeforeBundleCommand.js the file is created and written: 
```
var TEMP_FILE_PATH = path.join(require("os").tmpdir(), "CodePushResourcesMap.json");
// [ ... ]
fs.writeFile(TEMP_FILE_PATH, JSON .... 
```

later in scripts/generateBundledResourcesHash.js the file is read and removed: 
```
var TEMP_FILE_PATH = path.join(require("os").tmpdir(), "CodePushResourcesMap.json");
// [ ... ]
var oldFileToModifiedTimeMap = require(TEMP_FILE_PATH);
// [ ... ]
fs.unlinkSync(TEMP_FILE_PATH);
```

For us it happens quite often that multiple jobs are running in parallel, breaking each other. 
This is the sample output from the affected jenkins job:

```
[ ... ]
bundle: Done copying assets
:app:generateBundledResourcesHashLocalReleasemodule.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/CodePushResourcesMap.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/jenkins_home/workspace/239_cognito-logout-handling-S7T3KVECBPSJLFN6HQNB4IPKGNWPRYTU3HWBIQIZ6YVEAAKS4E6Q/node_modules/react-native-code-push/scripts/generateBundledResourcesHash.js:32:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateBundledResourcesHashLocalRelease'.
> Process 'command 'node'' finished with non-zero exit value 1
```

**Comment by webkodierer** [comment]
Oh, I'm very sorry, this is obviously the wrong github project, I wanted to address https://github.com/Microsoft/react-native-code-push
