### ISSUE TITLE
code-push without options yields "spawn ENAMETOOLONG" error

### ISSUE THREAD

**Issue by pocesar** [Microsoft/code-push#510]
```
F:\Users\Paulo>code-push -v
2.0.2-beta
F:\Users\Paulo>node -v
v8.4.0
F:\Users\Paulo>npm -v
4.6.1
```

when executing `code-push`, the following error appears:

```
 / ___/__  ___/ /__ / _ \__ _____ / /
/ /__/ _ \/ _  / -_) ___/ // (_-</ _ \
\___/\___/\_,_/\__/_/   \_,_/___/_//_/    CLI v2.0.2-beta
======================================

Mobile Center CodePush is a service that enables you to deploy mobile app updates directly to your users' devices.

  _____        __    ___           __
 / ___/__  ___/ /__ / _ \__ _____ / /
/ /__/ _ \/ _  / -_) ___/ // (_-</ _ \
\___/\___/\_,_/\__/_/   \_,_/___/_//_/    CLI v2.0.2-beta
======================================

Mobile Center CodePush is a service that enables you to deploy mobile app updates directly to your users' devices.

internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENAMETOOLONG
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at UpdateNotifier.check (C:\nodejs\node_modules\code-push-cli\node_modules\update-notifier\index.js:64:2)
    at module.exports (C:\nodejs\node_modules\code-push-cli\node_modules\update-notifier\index.js:124:17)
    at updateCheck (C:\nodejs\node_modules\code-push-cli\script\command-parser.js:33:20)
    at showHelp (C:\nodejs\node_modules\code-push-cli\script\command-parser.js:25:13)
    at Array.<anonymous> (C:\nodejs\node_modules\code-push-cli\script\command-parser.js:408:35)
    at Object.self.fail (C:\nodejs\node_modules\code-push-cli\node_modules\yargs\lib\usage.js:37:17)
    at Object.get [as argv] (C:\nodejs\node_modules\code-push-cli\node_modules\yargs\yargs.js:862:15)
```

Edit: for some odd reason, it seems that the `pkg` variable from `this.options` in includes the whole README.md in it https://github.com/yeoman/update-notifier/blob/master/index.js#L92

![image](https://user-images.githubusercontent.com/461084/30272838-bc8a7b1e-96cc-11e7-84d0-bdc9300852e9.png)

not sure whose fault is this, NPM, code-push or yeoman's update-notifier

**Comment by max-mironov** [comment]
Hi @pocesar, thanks for reporting this.
We've never seen such issues before, we'll try to reproduce it. Could you please provide us what exact version of update-notifier is installed? Also what platform you are on? Mac/windows/linux?

**Comment by pocesar** [comment]
Windows 10 x64

update-notifier is reported as being version 0.5.0

**Comment by max-mironov** [comment]
Hi there @pocesar,
I've tried to reproduce your issue with configuration provided by you but with no luck.

```
D:\Projects>code-push -v
2.0.2-beta

D:\Projects>node -v
v8.4.0

D:\Projects>npm -v
4.6.1

D:\Projects\code-push>code-push
  _____        __    ___           __
 / ___/__  ___/ /__ / _ \__ _____ / /
/ /__/ _ \/ _  / -_) ___/ // (_-</ _ \
\___/\___/\_,_/\__/_/   \_,_/___/_//_/    CLI v2.0.2-beta
======================================

Mobile Center CodePush is a service that enables you to deploy mobile app updates directly to your users' devices.

Usage: code-push <command>

Commands:
  access-key       View and manage the access keys associated with your account
  app              View and manage your CodePush apps
  collaborator     View and manage app collaborators
  debug            View the CodePush debug logs for a running app
  deployment       View and manage your app deployments
  link             Link an additional authentication provider (e.g. GitHub) to an existing Mobile Center account
  login            Authenticate in order to begin managing your apps
  logout           Log out of the current session
  patch            Update the metadata for an existing release
  promote          Promote the latest release from one app deployment to another
  register         Register a new Mobile Center account
  release          Release an update to an app deployment
  release-cordova  Release a Cordova update to an app deployment
  release-react    Release a React Native update to an app deployment
  rollback         Rollback the latest release for an app deployment
  whoami           Display the account info for the current login session

Options:
  -v, --version  Show version number  [boolean]


D:\Projects\code-push>
```

After executing `code-push` everything is working good for me. 
I'm also on WIndows10 Enterprise 64-bit, `update-notifier` is also 0.5.0.

I believe that we can close this issue at that moment and we will reopen it for sure if we have more info how to reproduce it or if we have more reports regarding this issue from other customers.

**Comment by aleyakovle** [comment]
Same issue
C:\Projects\ReactNative\MyProject>code-push -v
2.1.1-beta

C:\Projects\ReactNative\MyProject>node -v
v8.1.4

C:\Projects\ReactNative\MyProject>npm -v
5.5.1

```
C:\>code-push
  _____        __    ___           __ 
 / ___/__  ___/ /__ / _ \__ _____ / / 
/ /__/ _ \/ _  / -_) ___/ // (_-</ _ \
\___/\___/\_,_/\__/_/   \_,_/___/_//_/    CLI v2.1.1-beta
======================================

Mobile Center CodePush is a service that enables you to deploy mobile app updates directly to your users' devices.

  _____        __    ___           __ 
 / ___/__  ___/ /__ / _ \__ _____ / / 
/ /__/ _ \/ _  / -_) ___/ // (_-</ _ \
\___/\___/\_,_/\__/_/   \_,_/___/_//_/    CLI v2.1.1-beta
======================================

Mobile Center CodePush is a service that enables you to deploy mobile app updates directly to your users' devices.

internal/child_process.js:317
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at exports.spawn (child_process.js:491:9)
    at UpdateNotifier.check (C:\Users\deep\AppData\Roaming\npm\node_modules\code-push-cli\node_modules\update-notifier\index.js:64:2)
    at module.exports (C:\Users\deep\AppData\Roaming\npm\node_modules\code-push-cli\node_modules\update-notifier\index.js:124:17)
    at updateCheck (C:\Users\deep\AppData\Roaming\npm\node_modules\code-push-cli\script\command-parser.js:33:20)
    at showHelp (C:\Users\deep\AppData\Roaming\npm\node_modules\code-push-cli\script\command-parser.js:25:13)
    at Array.<anonymous> (C:\Users\deep\AppData\Roaming\npm\node_modules\code-push-cli\script\command-parser.js:410:35)
    at Object.self.fail (C:\Users\deep\AppData\Roaming\npm\node_modules\code-push-cli\node_modules\yargs\lib\usage.js:37:17)
    at Object.get [as argv] (C:\Users\deep\AppData\Roaming\npm\node_modules\code-push-cli\node_modules\yargs\yargs.js:862:15)

```
