### ISSUE TITLE
code-push-server register Not Found

### ISSUE THREAD

**Issue by liuziyuan** [microsoft/code-push#695]
1. I try to use code push cli to register from my private code push server (http://xxx.xxx.xxx.109:3000/), and then the address http://xxx.xxx.xxx.109:3000/auth/register? Hostname = XXXX was displayed in the browser. I filled in the username and password (the user's civil password is correct, and the password has also been modified). Then I clicked register, and there was no response. I opened F12 and saw that the POST request returned a 404 error. 

**Browser F12 Log:**
> 
Not Found
404
NotFoundError: Not Found
    at /usr/local/lib/node_modules/code-push-server/app.js:87:15
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7

**System Log:**

> 
7.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
[2020-01-15T15:46:18.183] [ERROR] cps:app - { NotFoundError: Not Found
    at /usr/local/lib/node_modules/code-push-server/app.js:87:15
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7 message: 'Not Found', name: 'NotFoundError', status: 404 }
[2020-01-15T15:46:18.184] [INFO] http - ::ffff:203.85.54.177 - - "POST /auth/register?hostname=DESKTOP-I700358 HTTP/1.1" 404 2969 "http://xx.xx.xxx.109:3000/auth/register?hostname=DESKTOP-I700358" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"

2. code-push-server version: 3.1.0

**Comment by pfleidi** [comment]
I'm sorry to say, but this CLI has been officially deprecated a while now and using private code-push server with it was nerver officially supported. This looks like an issue with your server and not with this project.

**Comment by Lemon-le** [comment]
> 1. I try to use code push cli to register from my private code push server (http://xxx.xxx.xxx.109:3000/), and then the address http://xxx.xxx.xxx.109:3000/auth/register? Hostname = XXXX was displayed in the browser. I filled in the username and password (the user's civil password is correct, and the password has also been modified). Then I clicked register, and there was no response. I opened F12 and saw that the POST request returned a 404 error.
> 
> **Browser F12 Log:**
> 
> > 
> 
> Not Found
> 404
> NotFoundError: Not Found
> at /usr/local/lib/node_modules/code-push-server/app.js:87:15
> at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
> at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
> at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
> at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
> at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
> at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
> at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
> 
> **System Log:**
> 
> > 
> 
> 7.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
> [2020-01-15T15:46:18.183] [ERROR] cps:app - { NotFoundError: Not Found
> at /usr/local/lib/node_modules/code-push-server/app.js:87:15
> at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
> at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
> at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
> at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
> at next (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
> at Function.handle (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
> at router (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
> at Layer.handle [as handle_request] (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
> at /usr/local/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7 message: 'Not Found', name: 'NotFoundError', status: 404 }
> [2020-01-15T15:46:18.184] [INFO] http - ::ffff:203.85.54.177 - - "POST /auth/register?hostname=DESKTOP-I700358 HTTP/1.1" 404 2969 "http://xx.xx.xxx.109:3000/auth/register?hostname=DESKTOP-I700358" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
> 
> 1. code-push-server version: 3.1.0

hi，你的这个问题解决了吗，遇到了同样的问题。
